<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DependencyGraph\DependencyGraph.csproj" />
    <ProjectReference Include="..\Formula\Formula.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CompilerTest">
      <HintPath>..\CompilerTest\bin\Debug\CompilerTest.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
